#!/bin/sh
######################################################
#
# Adds additional IPs to the loopback interface
#
#   Triggered on login via:
#   sudo defaults write com.apple.loginwindow LoginHook /usr/local/bin/addtl-lo
#
######################################################

ifconfig lo0 alias 127.0.0.2
ifconfig lo0 alias 127.0.0.3
ifconfig lo0 alias 127.0.0.4
ifconfig lo0 alias 127.0.0.10

#forward www ports from the new ip to the ones the vm is bound to
ipfw add fwd 127.0.0.1,40080 tcp from any to 127.0.0.2 80
ipfw add fwd 127.0.0.1,40080 tcp from any to 127.0.0.2 4001
ipfw add fwd 127.0.0.1,40090 tcp from any to 127.0.0.3 80

ipfw add fwd 127.0.0.1,50000 tcp from any to 127.0.0.10 80
